---
AWSTemplateFormatVersion: '2010-09-09'
# DG project info
Parameters:
  ProjectName:
    Type: String
    Default: Oculus
    Description: The name of the project.
  ProjectPOC:
    Type: String
    Default: Jay Miller
    Description: The point of contact for the project.
  ProjectWBSCode:
    Type: String
    Default: IIP.UNUMP2.15.CAP
    Description: The work breakdown structure code for the project.
  ProjectPONumber:
    Type: String
    Default: TBD
    Description: The purchase order number for the project.

# For Oculus queue
Resources:
  OculusQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OculusQueueDev
      Tags:
      - Key: Name
        Value: OCULUS-DEV-SQS
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: ProjectPOC
        Value: !Ref ProjectPOC
      - Key: ProjectWBSCode
        Value: !Ref ProjectWBSCode
      - Key: ProjectPONumber
        Value: !Ref ProjectPONumber
      - Key: ExpirationDate
        Value: !Ref ExpirationDate
Outputs:
  QueueName:
    Description: The name of the queue
    Value:
      Fn::GetAtt:
      - OculusQueue
      - QueueName
  QueueURL:
    Description: The URL of the queue
    Value: !Ref OculusQueue
  QueueARN:
    Description: The ARN of the queue
    Value:
      Fn::GetAtt:
      - OculusQueue
      - Arn
