---
AWSTemplateFormatVersion: '2010-09-09'

# For Oculus queue
# SQS doesnt support tags yet
# https://sqs.us-east-2.amazonaws.com/465688003075/OculusSQS
Resources:
  OculusQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OculusQueueDev
Outputs:
  QueueName:
    Description: The name of the queue
    Value:
      Fn::GetAtt:
      - OculusQueue
      - QueueName
  QueueURL:
    Description: The URL of the queue
    Value: !Ref OculusQueue
  QueueARN:
    Description: The ARN of the queue
    Value:
      Fn::GetAtt:
      - OculusQueue
      - Arn
